//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gift_Cards.GuestService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GuestSearchCriteria", Namespace="http://vo.externalUI.foundation.rccl.com")]
    [System.SerializableAttribute()]
    public partial class GuestSearchCriteria : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cruiseBookingIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Gift_Cards.GuestService.NameValuePair[] extraPropertiesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string firstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string folioNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string groupIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string guestIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string guestPhotoSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool includeGuestPhotoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime lastUpdateDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime sailDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string shipCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int stateroomNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vacationIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cruiseBookingId {
            get {
                return this.cruiseBookingIdField;
            }
            set {
                if ((object.ReferenceEquals(this.cruiseBookingIdField, value) != true)) {
                    this.cruiseBookingIdField = value;
                    this.RaisePropertyChanged("cruiseBookingId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Gift_Cards.GuestService.NameValuePair[] extraProperties {
            get {
                return this.extraPropertiesField;
            }
            set {
                if ((object.ReferenceEquals(this.extraPropertiesField, value) != true)) {
                    this.extraPropertiesField = value;
                    this.RaisePropertyChanged("extraProperties");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.firstNameField, value) != true)) {
                    this.firstNameField = value;
                    this.RaisePropertyChanged("firstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string folioNumber {
            get {
                return this.folioNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.folioNumberField, value) != true)) {
                    this.folioNumberField = value;
                    this.RaisePropertyChanged("folioNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string groupId {
            get {
                return this.groupIdField;
            }
            set {
                if ((object.ReferenceEquals(this.groupIdField, value) != true)) {
                    this.groupIdField = value;
                    this.RaisePropertyChanged("groupId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string guestId {
            get {
                return this.guestIdField;
            }
            set {
                if ((object.ReferenceEquals(this.guestIdField, value) != true)) {
                    this.guestIdField = value;
                    this.RaisePropertyChanged("guestId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string guestPhotoSize {
            get {
                return this.guestPhotoSizeField;
            }
            set {
                if ((object.ReferenceEquals(this.guestPhotoSizeField, value) != true)) {
                    this.guestPhotoSizeField = value;
                    this.RaisePropertyChanged("guestPhotoSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool includeGuestPhoto {
            get {
                return this.includeGuestPhotoField;
            }
            set {
                if ((this.includeGuestPhotoField.Equals(value) != true)) {
                    this.includeGuestPhotoField = value;
                    this.RaisePropertyChanged("includeGuestPhoto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.lastNameField, value) != true)) {
                    this.lastNameField = value;
                    this.RaisePropertyChanged("lastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime lastUpdateDate {
            get {
                return this.lastUpdateDateField;
            }
            set {
                if ((this.lastUpdateDateField.Equals(value) != true)) {
                    this.lastUpdateDateField = value;
                    this.RaisePropertyChanged("lastUpdateDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime sailDate {
            get {
                return this.sailDateField;
            }
            set {
                if ((this.sailDateField.Equals(value) != true)) {
                    this.sailDateField = value;
                    this.RaisePropertyChanged("sailDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string shipCode {
            get {
                return this.shipCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.shipCodeField, value) != true)) {
                    this.shipCodeField = value;
                    this.RaisePropertyChanged("shipCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int stateroomNumber {
            get {
                return this.stateroomNumberField;
            }
            set {
                if ((this.stateroomNumberField.Equals(value) != true)) {
                    this.stateroomNumberField = value;
                    this.RaisePropertyChanged("stateroomNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vacationId {
            get {
                return this.vacationIdField;
            }
            set {
                if ((object.ReferenceEquals(this.vacationIdField, value) != true)) {
                    this.vacationIdField = value;
                    this.RaisePropertyChanged("vacationId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NameValuePair", Namespace="http://vo.externalUI.foundation.rccl.com")]
    [System.SerializableAttribute()]
    public partial class NameValuePair : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string valueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                if ((object.ReferenceEquals(this.valueField, value) != true)) {
                    this.valueField = value;
                    this.RaisePropertyChanged("value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GuestView", Namespace="http://vo.externalUI.foundation.rccl.com")]
    [System.SerializableAttribute()]
    public partial class GuestView : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Gift_Cards.GuestService.FolioView activeFolioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string activeSeapassBarcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ageGroupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool allowChargeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime birthdayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cruiseBookingIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cruiseCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime debarkationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string deckField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string diningField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string diningTableSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string diningWaitListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime embarkationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string embarkationStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Gift_Cards.GuestService.NameValuePair[] extraPropertiesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string firstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string folioNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Gift_Cards.GuestService.FolioView[] foliosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string gatewayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string genderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string groupIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string guestIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long guestSequenceNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime lastChangeDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string loyaltyLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string loyaltyNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nationalityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime passportExpirationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passportNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool photoAvailableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] photoDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string photoMimeTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string photoURLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string primaryLanguageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime sailDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string salutationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Gift_Cards.GuestService.ArrayOfString seapassBarcodesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string shipCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool smokerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string stateroomNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string typeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool vipField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool wheelechairField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MI {
            get {
                return this.MIField;
            }
            set {
                if ((object.ReferenceEquals(this.MIField, value) != true)) {
                    this.MIField = value;
                    this.RaisePropertyChanged("MI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Gift_Cards.GuestService.FolioView activeFolio {
            get {
                return this.activeFolioField;
            }
            set {
                if ((object.ReferenceEquals(this.activeFolioField, value) != true)) {
                    this.activeFolioField = value;
                    this.RaisePropertyChanged("activeFolio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string activeSeapassBarcode {
            get {
                return this.activeSeapassBarcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.activeSeapassBarcodeField, value) != true)) {
                    this.activeSeapassBarcodeField = value;
                    this.RaisePropertyChanged("activeSeapassBarcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int age {
            get {
                return this.ageField;
            }
            set {
                if ((this.ageField.Equals(value) != true)) {
                    this.ageField = value;
                    this.RaisePropertyChanged("age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ageGroup {
            get {
                return this.ageGroupField;
            }
            set {
                if ((this.ageGroupField.Equals(value) != true)) {
                    this.ageGroupField = value;
                    this.RaisePropertyChanged("ageGroup");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool allowCharge {
            get {
                return this.allowChargeField;
            }
            set {
                if ((this.allowChargeField.Equals(value) != true)) {
                    this.allowChargeField = value;
                    this.RaisePropertyChanged("allowCharge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime birthday {
            get {
                return this.birthdayField;
            }
            set {
                if ((this.birthdayField.Equals(value) != true)) {
                    this.birthdayField = value;
                    this.RaisePropertyChanged("birthday");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cruiseBookingId {
            get {
                return this.cruiseBookingIdField;
            }
            set {
                if ((object.ReferenceEquals(this.cruiseBookingIdField, value) != true)) {
                    this.cruiseBookingIdField = value;
                    this.RaisePropertyChanged("cruiseBookingId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cruiseCount {
            get {
                return this.cruiseCountField;
            }
            set {
                if ((this.cruiseCountField.Equals(value) != true)) {
                    this.cruiseCountField = value;
                    this.RaisePropertyChanged("cruiseCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime debarkationDate {
            get {
                return this.debarkationDateField;
            }
            set {
                if ((this.debarkationDateField.Equals(value) != true)) {
                    this.debarkationDateField = value;
                    this.RaisePropertyChanged("debarkationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string deck {
            get {
                return this.deckField;
            }
            set {
                if ((object.ReferenceEquals(this.deckField, value) != true)) {
                    this.deckField = value;
                    this.RaisePropertyChanged("deck");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dining {
            get {
                return this.diningField;
            }
            set {
                if ((object.ReferenceEquals(this.diningField, value) != true)) {
                    this.diningField = value;
                    this.RaisePropertyChanged("dining");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string diningTableSize {
            get {
                return this.diningTableSizeField;
            }
            set {
                if ((object.ReferenceEquals(this.diningTableSizeField, value) != true)) {
                    this.diningTableSizeField = value;
                    this.RaisePropertyChanged("diningTableSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string diningWaitList {
            get {
                return this.diningWaitListField;
            }
            set {
                if ((object.ReferenceEquals(this.diningWaitListField, value) != true)) {
                    this.diningWaitListField = value;
                    this.RaisePropertyChanged("diningWaitList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime embarkationDate {
            get {
                return this.embarkationDateField;
            }
            set {
                if ((this.embarkationDateField.Equals(value) != true)) {
                    this.embarkationDateField = value;
                    this.RaisePropertyChanged("embarkationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string embarkationStatus {
            get {
                return this.embarkationStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.embarkationStatusField, value) != true)) {
                    this.embarkationStatusField = value;
                    this.RaisePropertyChanged("embarkationStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Gift_Cards.GuestService.NameValuePair[] extraProperties {
            get {
                return this.extraPropertiesField;
            }
            set {
                if ((object.ReferenceEquals(this.extraPropertiesField, value) != true)) {
                    this.extraPropertiesField = value;
                    this.RaisePropertyChanged("extraProperties");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.firstNameField, value) != true)) {
                    this.firstNameField = value;
                    this.RaisePropertyChanged("firstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string folioNumber {
            get {
                return this.folioNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.folioNumberField, value) != true)) {
                    this.folioNumberField = value;
                    this.RaisePropertyChanged("folioNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Gift_Cards.GuestService.FolioView[] folios {
            get {
                return this.foliosField;
            }
            set {
                if ((object.ReferenceEquals(this.foliosField, value) != true)) {
                    this.foliosField = value;
                    this.RaisePropertyChanged("folios");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string gateway {
            get {
                return this.gatewayField;
            }
            set {
                if ((object.ReferenceEquals(this.gatewayField, value) != true)) {
                    this.gatewayField = value;
                    this.RaisePropertyChanged("gateway");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string gender {
            get {
                return this.genderField;
            }
            set {
                if ((object.ReferenceEquals(this.genderField, value) != true)) {
                    this.genderField = value;
                    this.RaisePropertyChanged("gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string groupId {
            get {
                return this.groupIdField;
            }
            set {
                if ((object.ReferenceEquals(this.groupIdField, value) != true)) {
                    this.groupIdField = value;
                    this.RaisePropertyChanged("groupId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string guestId {
            get {
                return this.guestIdField;
            }
            set {
                if ((object.ReferenceEquals(this.guestIdField, value) != true)) {
                    this.guestIdField = value;
                    this.RaisePropertyChanged("guestId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long guestSequenceNumber {
            get {
                return this.guestSequenceNumberField;
            }
            set {
                if ((this.guestSequenceNumberField.Equals(value) != true)) {
                    this.guestSequenceNumberField = value;
                    this.RaisePropertyChanged("guestSequenceNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime lastChangeDate {
            get {
                return this.lastChangeDateField;
            }
            set {
                if ((this.lastChangeDateField.Equals(value) != true)) {
                    this.lastChangeDateField = value;
                    this.RaisePropertyChanged("lastChangeDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.lastNameField, value) != true)) {
                    this.lastNameField = value;
                    this.RaisePropertyChanged("lastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string loyaltyLevel {
            get {
                return this.loyaltyLevelField;
            }
            set {
                if ((object.ReferenceEquals(this.loyaltyLevelField, value) != true)) {
                    this.loyaltyLevelField = value;
                    this.RaisePropertyChanged("loyaltyLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string loyaltyNumber {
            get {
                return this.loyaltyNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.loyaltyNumberField, value) != true)) {
                    this.loyaltyNumberField = value;
                    this.RaisePropertyChanged("loyaltyNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nationality {
            get {
                return this.nationalityField;
            }
            set {
                if ((object.ReferenceEquals(this.nationalityField, value) != true)) {
                    this.nationalityField = value;
                    this.RaisePropertyChanged("nationality");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime passportExpirationDate {
            get {
                return this.passportExpirationDateField;
            }
            set {
                if ((this.passportExpirationDateField.Equals(value) != true)) {
                    this.passportExpirationDateField = value;
                    this.RaisePropertyChanged("passportExpirationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string passportNumber {
            get {
                return this.passportNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.passportNumberField, value) != true)) {
                    this.passportNumberField = value;
                    this.RaisePropertyChanged("passportNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool photoAvailable {
            get {
                return this.photoAvailableField;
            }
            set {
                if ((this.photoAvailableField.Equals(value) != true)) {
                    this.photoAvailableField = value;
                    this.RaisePropertyChanged("photoAvailable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] photoData {
            get {
                return this.photoDataField;
            }
            set {
                if ((object.ReferenceEquals(this.photoDataField, value) != true)) {
                    this.photoDataField = value;
                    this.RaisePropertyChanged("photoData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string photoMimeType {
            get {
                return this.photoMimeTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.photoMimeTypeField, value) != true)) {
                    this.photoMimeTypeField = value;
                    this.RaisePropertyChanged("photoMimeType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string photoURL {
            get {
                return this.photoURLField;
            }
            set {
                if ((object.ReferenceEquals(this.photoURLField, value) != true)) {
                    this.photoURLField = value;
                    this.RaisePropertyChanged("photoURL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string primaryLanguage {
            get {
                return this.primaryLanguageField;
            }
            set {
                if ((object.ReferenceEquals(this.primaryLanguageField, value) != true)) {
                    this.primaryLanguageField = value;
                    this.RaisePropertyChanged("primaryLanguage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime sailDate {
            get {
                return this.sailDateField;
            }
            set {
                if ((this.sailDateField.Equals(value) != true)) {
                    this.sailDateField = value;
                    this.RaisePropertyChanged("sailDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string salutation {
            get {
                return this.salutationField;
            }
            set {
                if ((object.ReferenceEquals(this.salutationField, value) != true)) {
                    this.salutationField = value;
                    this.RaisePropertyChanged("salutation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Gift_Cards.GuestService.ArrayOfString seapassBarcodes {
            get {
                return this.seapassBarcodesField;
            }
            set {
                if ((object.ReferenceEquals(this.seapassBarcodesField, value) != true)) {
                    this.seapassBarcodesField = value;
                    this.RaisePropertyChanged("seapassBarcodes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sect {
            get {
                return this.sectField;
            }
            set {
                if ((object.ReferenceEquals(this.sectField, value) != true)) {
                    this.sectField = value;
                    this.RaisePropertyChanged("sect");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string shipCode {
            get {
                return this.shipCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.shipCodeField, value) != true)) {
                    this.shipCodeField = value;
                    this.RaisePropertyChanged("shipCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool smoker {
            get {
                return this.smokerField;
            }
            set {
                if ((this.smokerField.Equals(value) != true)) {
                    this.smokerField = value;
                    this.RaisePropertyChanged("smoker");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string stateroomNumber {
            get {
                return this.stateroomNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.stateroomNumberField, value) != true)) {
                    this.stateroomNumberField = value;
                    this.RaisePropertyChanged("stateroomNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string status {
            get {
                return this.statusField;
            }
            set {
                if ((object.ReferenceEquals(this.statusField, value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                if ((object.ReferenceEquals(this.typeField, value) != true)) {
                    this.typeField = value;
                    this.RaisePropertyChanged("type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool vip {
            get {
                return this.vipField;
            }
            set {
                if ((this.vipField.Equals(value) != true)) {
                    this.vipField = value;
                    this.RaisePropertyChanged("vip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool wheelechair {
            get {
                return this.wheelechairField;
            }
            set {
                if ((this.wheelechairField.Equals(value) != true)) {
                    this.wheelechairField = value;
                    this.RaisePropertyChanged("wheelechair");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FolioView", Namespace="http://vo.externalUI.foundation.rccl.com")]
    [System.SerializableAttribute()]
    public partial class FolioView : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool allowChargeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string barcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool currentFolioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string deckField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime effectiveDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int folioIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string folioNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long guestIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long guestSequenceNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ownerFacilityCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool photoExistsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string shipCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string stateroomNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string targetCriteriaKeyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool allowCharge {
            get {
                return this.allowChargeField;
            }
            set {
                if ((this.allowChargeField.Equals(value) != true)) {
                    this.allowChargeField = value;
                    this.RaisePropertyChanged("allowCharge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string barcode {
            get {
                return this.barcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.barcodeField, value) != true)) {
                    this.barcodeField = value;
                    this.RaisePropertyChanged("barcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool currentFolio {
            get {
                return this.currentFolioField;
            }
            set {
                if ((this.currentFolioField.Equals(value) != true)) {
                    this.currentFolioField = value;
                    this.RaisePropertyChanged("currentFolio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string deck {
            get {
                return this.deckField;
            }
            set {
                if ((object.ReferenceEquals(this.deckField, value) != true)) {
                    this.deckField = value;
                    this.RaisePropertyChanged("deck");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime effectiveDate {
            get {
                return this.effectiveDateField;
            }
            set {
                if ((this.effectiveDateField.Equals(value) != true)) {
                    this.effectiveDateField = value;
                    this.RaisePropertyChanged("effectiveDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int folioId {
            get {
                return this.folioIdField;
            }
            set {
                if ((this.folioIdField.Equals(value) != true)) {
                    this.folioIdField = value;
                    this.RaisePropertyChanged("folioId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string folioNumber {
            get {
                return this.folioNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.folioNumberField, value) != true)) {
                    this.folioNumberField = value;
                    this.RaisePropertyChanged("folioNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long guestId {
            get {
                return this.guestIdField;
            }
            set {
                if ((this.guestIdField.Equals(value) != true)) {
                    this.guestIdField = value;
                    this.RaisePropertyChanged("guestId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long guestSequenceNumber {
            get {
                return this.guestSequenceNumberField;
            }
            set {
                if ((this.guestSequenceNumberField.Equals(value) != true)) {
                    this.guestSequenceNumberField = value;
                    this.RaisePropertyChanged("guestSequenceNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ownerFacilityCode {
            get {
                return this.ownerFacilityCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ownerFacilityCodeField, value) != true)) {
                    this.ownerFacilityCodeField = value;
                    this.RaisePropertyChanged("ownerFacilityCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool photoExists {
            get {
                return this.photoExistsField;
            }
            set {
                if ((this.photoExistsField.Equals(value) != true)) {
                    this.photoExistsField = value;
                    this.RaisePropertyChanged("photoExists");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sect {
            get {
                return this.sectField;
            }
            set {
                if ((object.ReferenceEquals(this.sectField, value) != true)) {
                    this.sectField = value;
                    this.RaisePropertyChanged("sect");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string shipCode {
            get {
                return this.shipCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.shipCodeField, value) != true)) {
                    this.shipCodeField = value;
                    this.RaisePropertyChanged("shipCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string stateroomNumber {
            get {
                return this.stateroomNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.stateroomNumberField, value) != true)) {
                    this.stateroomNumberField = value;
                    this.RaisePropertyChanged("stateroomNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string targetCriteriaKey {
            get {
                return this.targetCriteriaKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.targetCriteriaKeyField, value) != true)) {
                    this.targetCriteriaKeyField = value;
                    this.RaisePropertyChanged("targetCriteriaKey");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://party.service.externalUI.foundation.rccl.com", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GuestViewSessionPage", Namespace="http://vo.externalUI.foundation.rccl.com")]
    [System.SerializableAttribute()]
    public partial class GuestViewSessionPage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int guestCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Gift_Cards.GuestService.GuestView[] guestsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime maxLastChangeDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int pageCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sessionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int startIndexField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int guestCount {
            get {
                return this.guestCountField;
            }
            set {
                if ((this.guestCountField.Equals(value) != true)) {
                    this.guestCountField = value;
                    this.RaisePropertyChanged("guestCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Gift_Cards.GuestService.GuestView[] guests {
            get {
                return this.guestsField;
            }
            set {
                if ((object.ReferenceEquals(this.guestsField, value) != true)) {
                    this.guestsField = value;
                    this.RaisePropertyChanged("guests");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime maxLastChangeDate {
            get {
                return this.maxLastChangeDateField;
            }
            set {
                if ((this.maxLastChangeDateField.Equals(value) != true)) {
                    this.maxLastChangeDateField = value;
                    this.RaisePropertyChanged("maxLastChangeDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int pageCount {
            get {
                return this.pageCountField;
            }
            set {
                if ((this.pageCountField.Equals(value) != true)) {
                    this.pageCountField = value;
                    this.RaisePropertyChanged("pageCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sessionId {
            get {
                return this.sessionIdField;
            }
            set {
                if ((object.ReferenceEquals(this.sessionIdField, value) != true)) {
                    this.sessionIdField = value;
                    this.RaisePropertyChanged("sessionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int startIndex {
            get {
                return this.startIndexField;
            }
            set {
                if ((this.startIndexField.Equals(value) != true)) {
                    this.startIndexField = value;
                    this.RaisePropertyChanged("startIndex");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://party.service.externalUI.foundation.rccl.com", ConfigurationName="GuestService.GuestServicePortType")]
    public interface GuestServicePortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        void disposeSession(string sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="GuestView")]
        Gift_Cards.GuestService.GuestView[] getGuestsForSailing(Gift_Cards.GuestService.GuestSearchCriteria searchParams);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="GuestViewSessionPage")]
        Gift_Cards.GuestService.GuestViewSessionPage createSession(Gift_Cards.GuestService.GuestSearchCriteria searchParams);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        int getGuestCount(Gift_Cards.GuestService.GuestSearchCriteria searchParams);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="GuestViewSessionPage")]
        Gift_Cards.GuestService.GuestViewSessionPage getSessionPage(string sessionId, int startIndex, int maxCount);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GuestServicePortTypeChannel : Gift_Cards.GuestService.GuestServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GuestServicePortTypeClient : System.ServiceModel.ClientBase<Gift_Cards.GuestService.GuestServicePortType>, Gift_Cards.GuestService.GuestServicePortType {
        
        public GuestServicePortTypeClient() {
        }
        
        public GuestServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GuestServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GuestServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GuestServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void disposeSession(string sessionId) {
            base.Channel.disposeSession(sessionId);
        }
        
        public Gift_Cards.GuestService.GuestView[] getGuestsForSailing(Gift_Cards.GuestService.GuestSearchCriteria searchParams) {
            return base.Channel.getGuestsForSailing(searchParams);
        }
        
        public Gift_Cards.GuestService.GuestViewSessionPage createSession(Gift_Cards.GuestService.GuestSearchCriteria searchParams) {
            return base.Channel.createSession(searchParams);
        }
        
        public int getGuestCount(Gift_Cards.GuestService.GuestSearchCriteria searchParams) {
            return base.Channel.getGuestCount(searchParams);
        }
        
        public Gift_Cards.GuestService.GuestViewSessionPage getSessionPage(string sessionId, int startIndex, int maxCount) {
            return base.Channel.getSessionPage(sessionId, startIndex, maxCount);
        }
    }
}
