//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gift_Cards.VoyageService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VoyageView", Namespace="http://vo.externalUI.foundation.rccl.com")]
    [System.SerializableAttribute()]
    public partial class VoyageView : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool activeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string brandCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string colorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dispatchCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string itineraryCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime itineraryEffectiveDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Gift_Cards.VoyageService.ItineraryView itineraryViewField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int numberOfDaysField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pmsVoyageIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string regionCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime returnDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string shipCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string shipCurrencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime startDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int startDateIntField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string subRegionCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int voyageNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool active {
            get {
                return this.activeField;
            }
            set {
                if ((this.activeField.Equals(value) != true)) {
                    this.activeField = value;
                    this.RaisePropertyChanged("active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string brandCode {
            get {
                return this.brandCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.brandCodeField, value) != true)) {
                    this.brandCodeField = value;
                    this.RaisePropertyChanged("brandCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string colorCode {
            get {
                return this.colorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.colorCodeField, value) != true)) {
                    this.colorCodeField = value;
                    this.RaisePropertyChanged("colorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dispatchCode {
            get {
                return this.dispatchCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.dispatchCodeField, value) != true)) {
                    this.dispatchCodeField = value;
                    this.RaisePropertyChanged("dispatchCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string itineraryCode {
            get {
                return this.itineraryCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.itineraryCodeField, value) != true)) {
                    this.itineraryCodeField = value;
                    this.RaisePropertyChanged("itineraryCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime itineraryEffectiveDate {
            get {
                return this.itineraryEffectiveDateField;
            }
            set {
                if ((this.itineraryEffectiveDateField.Equals(value) != true)) {
                    this.itineraryEffectiveDateField = value;
                    this.RaisePropertyChanged("itineraryEffectiveDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Gift_Cards.VoyageService.ItineraryView itineraryView {
            get {
                return this.itineraryViewField;
            }
            set {
                if ((object.ReferenceEquals(this.itineraryViewField, value) != true)) {
                    this.itineraryViewField = value;
                    this.RaisePropertyChanged("itineraryView");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int numberOfDays {
            get {
                return this.numberOfDaysField;
            }
            set {
                if ((this.numberOfDaysField.Equals(value) != true)) {
                    this.numberOfDaysField = value;
                    this.RaisePropertyChanged("numberOfDays");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pmsVoyageId {
            get {
                return this.pmsVoyageIdField;
            }
            set {
                if ((object.ReferenceEquals(this.pmsVoyageIdField, value) != true)) {
                    this.pmsVoyageIdField = value;
                    this.RaisePropertyChanged("pmsVoyageId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string regionCode {
            get {
                return this.regionCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.regionCodeField, value) != true)) {
                    this.regionCodeField = value;
                    this.RaisePropertyChanged("regionCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime returnDate {
            get {
                return this.returnDateField;
            }
            set {
                if ((this.returnDateField.Equals(value) != true)) {
                    this.returnDateField = value;
                    this.RaisePropertyChanged("returnDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string shipCode {
            get {
                return this.shipCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.shipCodeField, value) != true)) {
                    this.shipCodeField = value;
                    this.RaisePropertyChanged("shipCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string shipCurrency {
            get {
                return this.shipCurrencyField;
            }
            set {
                if ((object.ReferenceEquals(this.shipCurrencyField, value) != true)) {
                    this.shipCurrencyField = value;
                    this.RaisePropertyChanged("shipCurrency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime startDate {
            get {
                return this.startDateField;
            }
            set {
                if ((this.startDateField.Equals(value) != true)) {
                    this.startDateField = value;
                    this.RaisePropertyChanged("startDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int startDateInt {
            get {
                return this.startDateIntField;
            }
            set {
                if ((this.startDateIntField.Equals(value) != true)) {
                    this.startDateIntField = value;
                    this.RaisePropertyChanged("startDateInt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string subRegionCode {
            get {
                return this.subRegionCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.subRegionCodeField, value) != true)) {
                    this.subRegionCodeField = value;
                    this.RaisePropertyChanged("subRegionCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int voyageNumber {
            get {
                return this.voyageNumberField;
            }
            set {
                if ((this.voyageNumberField.Equals(value) != true)) {
                    this.voyageNumberField = value;
                    this.RaisePropertyChanged("voyageNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ItineraryView", Namespace="http://vo.externalUI.foundation.rccl.com")]
    [System.SerializableAttribute()]
    public partial class ItineraryView : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string itineraryCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Gift_Cards.VoyageService.ItineraryStopView[] stopsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string itineraryCode {
            get {
                return this.itineraryCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.itineraryCodeField, value) != true)) {
                    this.itineraryCodeField = value;
                    this.RaisePropertyChanged("itineraryCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Gift_Cards.VoyageService.ItineraryStopView[] stops {
            get {
                return this.stopsField;
            }
            set {
                if ((object.ReferenceEquals(this.stopsField, value) != true)) {
                    this.stopsField = value;
                    this.RaisePropertyChanged("stops");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ItineraryStopView", Namespace="http://vo.externalUI.foundation.rccl.com")]
    [System.SerializableAttribute()]
    public partial class ItineraryStopView : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime arrivalDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int arrivalDayNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long arrivalTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long debarkationTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime departureDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int departureDayNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long departureTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long embarkationTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Gift_Cards.VoyageService.LocationView locationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tetheredField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime arrivalDateTime {
            get {
                return this.arrivalDateTimeField;
            }
            set {
                if ((this.arrivalDateTimeField.Equals(value) != true)) {
                    this.arrivalDateTimeField = value;
                    this.RaisePropertyChanged("arrivalDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int arrivalDayNumber {
            get {
                return this.arrivalDayNumberField;
            }
            set {
                if ((this.arrivalDayNumberField.Equals(value) != true)) {
                    this.arrivalDayNumberField = value;
                    this.RaisePropertyChanged("arrivalDayNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long arrivalTime {
            get {
                return this.arrivalTimeField;
            }
            set {
                if ((this.arrivalTimeField.Equals(value) != true)) {
                    this.arrivalTimeField = value;
                    this.RaisePropertyChanged("arrivalTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long debarkationTime {
            get {
                return this.debarkationTimeField;
            }
            set {
                if ((this.debarkationTimeField.Equals(value) != true)) {
                    this.debarkationTimeField = value;
                    this.RaisePropertyChanged("debarkationTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime departureDateTime {
            get {
                return this.departureDateTimeField;
            }
            set {
                if ((this.departureDateTimeField.Equals(value) != true)) {
                    this.departureDateTimeField = value;
                    this.RaisePropertyChanged("departureDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int departureDayNumber {
            get {
                return this.departureDayNumberField;
            }
            set {
                if ((this.departureDayNumberField.Equals(value) != true)) {
                    this.departureDayNumberField = value;
                    this.RaisePropertyChanged("departureDayNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long departureTime {
            get {
                return this.departureTimeField;
            }
            set {
                if ((this.departureTimeField.Equals(value) != true)) {
                    this.departureTimeField = value;
                    this.RaisePropertyChanged("departureTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long embarkationTime {
            get {
                return this.embarkationTimeField;
            }
            set {
                if ((this.embarkationTimeField.Equals(value) != true)) {
                    this.embarkationTimeField = value;
                    this.RaisePropertyChanged("embarkationTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Gift_Cards.VoyageService.LocationView location {
            get {
                return this.locationField;
            }
            set {
                if ((object.ReferenceEquals(this.locationField, value) != true)) {
                    this.locationField = value;
                    this.RaisePropertyChanged("location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tethered {
            get {
                return this.tetheredField;
            }
            set {
                if ((object.ReferenceEquals(this.tetheredField, value) != true)) {
                    this.tetheredField = value;
                    this.RaisePropertyChanged("tethered");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LocationView", Namespace="http://vo.externalUI.foundation.rccl.com")]
    [System.SerializableAttribute()]
    public partial class LocationView : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string locationTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string code {
            get {
                return this.codeField;
            }
            set {
                if ((object.ReferenceEquals(this.codeField, value) != true)) {
                    this.codeField = value;
                    this.RaisePropertyChanged("code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string locationType {
            get {
                return this.locationTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.locationTypeField, value) != true)) {
                    this.locationTypeField = value;
                    this.RaisePropertyChanged("locationType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://voyage.service.externalUI.foundation.rccl.com", ConfigurationName="VoyageService.VoyageServicePortType")]
    public interface VoyageServicePortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="VoyageView")]
        Gift_Cards.VoyageService.VoyageView getCurrentVoyage(string shipCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="VoyageView")]
        Gift_Cards.VoyageService.VoyageView[] getRecentVoyages(string shipCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="VoyageView")]
        Gift_Cards.VoyageService.VoyageView getVoyage(string shipCode, System.DateTime sailDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="VoyageView")]
        Gift_Cards.VoyageService.VoyageView getVoyageNumber(string voyageNumber);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface VoyageServicePortTypeChannel : Gift_Cards.VoyageService.VoyageServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VoyageServicePortTypeClient : System.ServiceModel.ClientBase<Gift_Cards.VoyageService.VoyageServicePortType>, Gift_Cards.VoyageService.VoyageServicePortType {
        
        public VoyageServicePortTypeClient() {
        }
        
        public VoyageServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VoyageServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VoyageServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VoyageServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Gift_Cards.VoyageService.VoyageView getCurrentVoyage(string shipCode) {
            return base.Channel.getCurrentVoyage(shipCode);
        }
        
        public Gift_Cards.VoyageService.VoyageView[] getRecentVoyages(string shipCode) {
            return base.Channel.getRecentVoyages(shipCode);
        }
        
        public Gift_Cards.VoyageService.VoyageView getVoyage(string shipCode, System.DateTime sailDate) {
            return base.Channel.getVoyage(shipCode, sailDate);
        }
        
        public Gift_Cards.VoyageService.VoyageView getVoyageNumber(string voyageNumber) {
            return base.Channel.getVoyageNumber(voyageNumber);
        }
    }
}
